test:
  image:
    registry: docker.io
    repository: busybox

image:
  registry: ko.local
  repository: github.com/nsathyaseelan/kyverno/cmd/kyverno

initImage:
  registry: ko.local
  repository: github.com/nsathyaseelan/kyverno/cmd/initcontainer
